### ISSUE TITLE
After the modbus device connects to the mapper, the container of the mapper fails.

### ISSUE THREAD

**Issue by NicoleLeeuu** [kubeedge/mappers-go#108]
The Modbus Mapper is running normally.  After the device is delivered, the container of the mapper fails.
![微信图片_20230731171819](https://github.com/kubeedge/mappers-go/assets/59806231/98d8dd81-499f-4cd3-8afe-18b15b3c4561)
View the mapper log. The command output is "panic: runtime error: invalid memory address or nil pointer dereference".
![微信图片_20230731170900](https://github.com/kubeedge/mappers-go/assets/59806231/87a5c285-3b7e-4dcd-b64b-937058ea54ca)
Locate the problem. It was found that the payload in the Run() function, located in the mappers/modbus-dmi/device/twindata.go file, did not add the "Expected" data section. This results in an error when accessing msg.Twin.Expected when executing the parse.ConvMsgTwinToGrpc(msg.Twin) function.
Is this a bug in the process of design and implementation?  If so, please leave bugfix matters to me.

**Comment by QiQi-OvO** [comment]
Yes, this is a bug that has been fixed by two PRs(https://github.com/kubeedge/mappers-go/pull/99, https://github.com/kubeedge/mappers-go/pull/105), but they haven't been merged into the code repository yet.

**Comment by cl2017** [comment]
> Yes, this is a bug that has been fixed by two PRs(#99, #105), but they haven't been merged into the code repository yet.

Let's review these PRs again and merged it into master
