### ISSUE TITLE
Create mapper template

### ISSUE THREAD

**Issue by sailorvii** [kubeedge/mappers-go#14]
Create a template for a customized mapper to ease the mapper development.

**Comment by sailorvii** [comment]
Target:
The user specifies the new mapper's name, then automatically creates a folder accordingly to the name. The User needs to write several functions, then the mapper works.

Detailed design:
1. Template files.
The file tree is like that:
- <nameOfNewMapper>
   - main.go
   - Dockerfile ---- Combine building code and container image.
   - deployment.yaml
   - config.yaml  
   - driver     ---- This is for reading/writing devices.  
     - client.go    -----  Fill in the functions like getting register/setting register.
   - device    ---- Device management. Such as reading the device configuration and create the data structure accordingly, connecting the devices, and reading/writing device registers.
     - device.go  ---- Almost need not much change except the initialization of driver client and customized visitor parsing.
     - devstatus.go
     - twindata.go
  - configmap
    - type.go   ---- Add the mapper-specific data structure.
    - parse.go
  - globals  ---- Global definitions.
    - globals.go
2. Tool to create the code.
   Use a shell script to get inputted mapper name, copy the template files to a new folder named as input. Replace the related file name, also replace some characters as input.

**Comment by ttlv** [comment]
well, this template is just for some protocols which are suppotted C/S,if some protocols are not suppotted C/S,the file client.go is useless.

**Comment by sailorvii** [comment]
If not the C/S structure, the client.go is also for getting/setting the device. For example, in modbus rtu mode, the client is to open serial devices and get/set them.
