### ISSUE TITLE
why mapper Twin structure has PropertyVisitor field

### ISSUE THREAD

**Issue by gy95** [kubeedge/mappers-go#36]
why mapper `Twin` structure has `PropertyVisitor` field, on the cloud side, this `Twin` structure only has three fields except `PropertyVisitor`
```
type Twin struct {
	PropertyName string `json:"propertyName,omitempty"`
	PVisitor     *PropertyVisitor
	Desired      DesiredData  `json:"desired,omitempty"`
	Reported     ReportedData `json:"reported,omitempty"`
}
```

**Comment by sailorvii** [comment]
This element is a pointer used for finding the visitor directly. It's not in the configmap or json files.

**Comment by gy95** [comment]
> This element is a pointer used for finding the visitor directly. It's not in the configmap or json files.

Got it, thanks a lot
