### ISSUE TITLE
failed to build modbus image

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/mappers-go#6]
Ref https://github.com/kubeedge/kubeedge/issues/2512

/assign @sailorvii

**Comment by sailorvii** [comment]
Please try to make the image in the directory "kubeedge/mappers-go" with command:
make modbusmapper_image

Example:
![image](https://user-images.githubusercontent.com/35483373/104697398-aad1ba80-574a-11eb-8e79-50ef7bd0989f.png)
