### ISSUE TITLE
a proposal for mapper-sdk

### ISSUE THREAD

**Issue by QiQi-OvO** [kubeedge/mappers-go#69]
Hi guys, we have make a proposal for mapper-sdk, which provides a more efficient method for accessing a new protocol.

**What would you like to be added/modified:**
1. Add mapper-sdk.
2. Provide a RESTful API.

**Why we need it:**
1. Now there are a lot of reusable parts in mapper's code. Mapper-sdk encapsulates these parts into functions to help developers reduce such meaningless things. 
2. Mqtt does not support the transmission of large packets of data. The RESTful API can alleviate this problem.

The preliminary plan can be viewed in the following documents :)
https://docs.google.com/document/d/1KrsFfPP8KZ33al3iB4g8hNWxi4sKtOWkkizLFyQAHSE/edit?usp=sharing

The preliminary code can be found in the following repository :)
https://github.com/QiQi-OvO/mappers-go

Welcome to discuss more details about this proposal and give some suggestions，thanks.

**Comment by RyanZhaoXB** [comment]
Hello, Qi. your proposal about mapper-sdk has been discussed for several times on the Device-IoT SIG Meeting.  this proposal is very impressive and has attracted a lot of attention. could you please make a pr for it? we will review your code in the community. please make sure that the basic function works and every check-item is clear.
